### ISSUE TITLE
Take learnings from Web Almanac site and apply to main httparchive site

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/httparchive.org#250]
We learned a lot from making the Web Almanac site and it follows a lot of best practices, particularly in terms of Accessibility, Performance, SEO and automation to ensure we stay at the top of that.

We should bring those learnings here and align the web sites, which will also make them easier to maintain together.

Making a list so I don't forget anything:
- [x] - Move Virtual Env to `.venv` to prevent linking problems - #241 
- [x] - Add robots.txt and sitemap.xml - #243 
- [x] - Add GitHub SuperLinter - #244 
- [x] - Rename `master` branch to `main` - #245 
- [x] - Add CodeQL scanning for JS and Python files to supplement Super Linter - #246 and #247 
- [x] - Add test script and run it in an action #248
- [x] - Update all dev dependencies and automate #249  
- [ ] - Look at whether to remove Babel? Is it really needed as quite chunky an d adds a lot of dependencies
- [ ] - Look at whether to remove Bootstrap - do we really need it?
- [ ] - Might need another normalize CSS script if we do remove Bootstrap.
- [ ] - Add metadata for SEO reason (see also #34 )
- [ ] - Set `rel="canonical"` on reports to avoid query param versions getting indexed.
- [ ] - Set `noindex` when not using httparchive.org domain to avoid GCP version getting indexed
- [ ] - Add Lighthouse tests on pull request
- [ ] - Lighthouse review
- [ ] - Look at CSP
- [ ] - Look at colour contrast
- [ ] - Move to `em`/`rem` based sizes to allow rescaling.
- [ ] - Accessibility review
- [ ] - Performance review
- [ ] - SEO review
- [ ] - Add web-vitals script?
- [ ] - Refactor Python scripts to organise into a `server` directory
- [ ] - Add pytest (ideally with 100% coverage!)

Feel free to add to this as you see fit, and grab some if they seem of interest. I'll start will work my way through them anyway.

**Comment by bazzadp** [comment]
Made quite a bit of progress with this, however the Accessibility improvements in particular have necessitated some changes:

- Some of the text had bad colour contrast, including the sub-headings:

![image](https://user-images.githubusercontent.com/10931297/116013841-24baef00-a62a-11eb-8856-53347037aa44.png)

and the table headings:

![image](https://user-images.githubusercontent.com/10931297/116013852-37cdbf00-a62a-11eb-934f-93ca89d252a2.png)

And our links:

![image](https://user-images.githubusercontent.com/10931297/116013868-4ae08f00-a62a-11eb-81be-f3e0b0eaf3d5.png)

Made them dark enough to pass colour-contrast checkers, which maybe doesn't follow the original style - the sub headings are now the same colour but I couldn't get a grey that passed:

![image](https://user-images.githubusercontent.com/10931297/116013923-a14dcd80-a62a-11eb-97ff-637133633b7b.png)

The links also blend in a bit more to the text when darker, but I brought back the underlines (except for menu links) which helps:

![image](https://user-images.githubusercontent.com/10931297/116013946-b62a6100-a62a-11eb-8cf7-1c1d8c139b4a.png)

Also a lot of the links had the same names ("View reports", "Learn more"...etc.) so made them a bit more descriptive.

Also added a few missing `<h1>s` which sometimes resulted in a slight style change.

Other than those, most of the above changes shouldn't result in any noticeable change (except to AT users and search engine crawlers!).

@rviscomi once we decide on #256 could you give this a a good going over (as quite a lot of change!) and then let's do a release?

**Comment by rviscomi** [comment]
Sounds good. Thanks for working on this—these are some long-overdue improvements! 🙌

**Comment by bazzadp** [comment]
OK merged everything I'm gonna merge for now. If you could have a good look over it @rviscomi that would be good.
